app = "rust-online-judge"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "online_judge"
  destination = "/judge"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
